### ISSUE TITLE
Picodrive keeps on crashing when selecting a rom

### ISSUE THREAD

**Issue by DolphinCube** [gameblabla/picodrive-nspire#2]
Hiya! I keep on trying to run Picodrive. when I load it after that and choose a game. It just crashes then restarts the system! I use the .md file type for my sega genesis games (yes I added a .tns at the end) and I removed the intros myself. So I tried to use Nover 3. But that just crashes it too. It says I have to use "compatibility mode¨ when I boot it up. Please help me out!

**Comment by gameblabla** [comment]
What games are you trying to run ? I just updated Picodrive with the new Service pack, did you just update it ? It's possible that the newer binary does not work. (i admit i haven't tried it myself)

**Comment by DolphinCube** [comment]
well.... I ran sonic 2 with the MD format (and they are my own dumps). And now that I just updated it. It is running! But extremely laggy though. How to fix?

**Comment by gameblabla** [comment]
@TheAutisticGamer Btw sorry, Latest Service pack fixed the slowdown issue in picodrive thanks to A600. You should give it a try.

**Comment by DolphinCube** [comment]
XD I forgot where the download link is. I'm so sorry!

**Comment by gameblabla** [comment]
http://boards.dingoonity.org/ingenic-jz4760-devices/uselessrs97-internal-firmware-for-revision-2-1/
It's here, grab the service pack for your firmware release. Note that i'll soon release a newer firmware so it might be preferable if you just wait. (i'm fixing other stuff too besides picodrive)

**Comment by gameblabla** [comment]
@TheAutisticGamer Discard what i said, i'm a complete idiot and mixed up things.
Picodrive was known not to work on the TI-Nspire CX.
However, i've just recently fixed it for that platform
[https://github.com/gameblabla/picodrive-nspire/raw/master/platform/nspire/picodrive-nspire.zip](https://github.com/gameblabla/picodrive-nspire/raw/master/platform/nspire/picodrive-nspire.zip)

Sorry for the confusion, i thought you were talking about Picodrive for another platform and not the nspire...
