### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by rhit-painteza** [gameblabla/picodrive-nspire#5]
Looking at getting a new version of this as the pre-compiled ones are outdated. Any special build instructions? I'm new to this.

**Comment by gameblabla** [comment]
I have released an updated build on picodrive :
https://tiplanet.org/forum/archives_voir.php?id=304358

However, there is currently an issue with the vsync code that does not seem to work properly on CX2 hardware. (but it still works despite that)

To compile it, you just need to compile the ndless-sdk, export the path and run make in platform/nspire

**Comment by rhit-painteza** [comment]
Awesome, thank you!
